### PR TITLE
v1.0-dev bug fixes

### LINKED ISSUE #89: Y-axis sort when highlighting
When a highlight is active the user cannot sort the y axis.

### LINKED ISSUE #90: Styling Issues for Y- Axis grouping
This happens when alphanumeric is chosen in the y-axis sort dropdown box.

### LINKED ISSUE #91: Can Only Sort Y-Axis Once
When highlight is active you cannot sort the Y-Axis (issue #89), but with no highlighting the user can only sort the Y-Axis once.

### LINKED ISSUE #92: Styling Issues for Meta Data
For the following regression test; "Confirm that hovering the mouse over a data point displays metadata (the name of the event, the day the event started, the day the event stopped) about that point", in IE the meta data is displaying in one line instead of being displayed in multiple line like in Chrome and Firefox.

### LINKED ISSUE #93: No Vertical Lines Appearing
No vertical lines appear in IE and Firefox with the following settings:

{"referenceLines":[{"studyDay":100,"label":"More than 99"},150]}

### LINKED ISSUE #95: Styling Issues for Participant View
The participant view in IE looks like this:

### LINKED ISSUE #96: Highlight within participant view
The user cannot use the highlighting feature within the participant view.

### LINKED ISSUE #97: Exportable Setting not working
I am still able to export the CSV with the following settings:

{"listingConfig":{"searchable":false,"sortable":false,"pagination":false,"exportable":false}}

### PR DESCRIPTION
**Pull request by samussiah**
Closes #89 
Closes #90 
Closes #91 
Closes #92 
Closes #93 
Closes #95 
Closes #96 
Closes #97

### CODE REVIEW

File: src/callbacks/onResize.js [hunk 1]
```diff
@@ -82,25 +82,39 @@ export default function onResize() {
...
-                .split('(')[1]},
-            ${+bottomXaxisTitle
-                .attr('transform')
-                .split(',')[1]
-                .split(')')[0] -
-                7 * this.margin.bottom / 16})`
+        `translate(${bottomXaxisTitleTransformX},${bottomXaxisTitleTransformY -
+            7 * this.margin.bottom / 16})`
     );
+
```
Comment (jwildfire) [inline src/callbacks/onResize.js]: Did this end up fixing the IE line break bug?

File: src/callbacks/onResize.js [hunk 2]
```diff
@@ -82,25 +82,39 @@ export default function onResize() {
...
     const bottomXaxis = this.svg.select('.x.axis'),
-        bottomXaxisTitle = bottomXaxis.select('.axis-title');
-    bottomXaxis.attr(
-        'transform',
-        `translate(0,${+bottomXaxis
-            .attr('transform')
-            .split(',')[1]
-            .split(')')[0] + this.y.rangeBand()})`
-    );
+        bottomXaxisTransform = bottomXaxis.attr('transform'),
```
Comment (jwildfire) [inline src/callbacks/onResize.js]: Not really sure what all this action is about - add a comment?

File: src/defaults/settings.js [hunk 3]
```diff
@@ -84,5 +84,5 @@ export default //Renderer-specific settings
     gridlines: 'y',
     range_band: 24,
     margin: { top: 50 }, // for second x-axis
-    resizable: true
+    resizable: false
```
Comment (jwildfire) [inline src/defaults/settings.js]: why'd we change resizable to false?

File: src/callbacks/onResize.js (hunk 2 above)
Comment (samussiah) [reply src/callbacks/onResize.js]: I'm dropping the bottom x-axis by a rangeBand so that the final ID doesn't draw over the x-axis.

File: src/callbacks/onResize.js (hunk 1 above)
Comment (samussiah) [reply src/callbacks/onResize.js]: I couldn't find a solution so I just inserted a nice separator string.

File: src/defaults/settings.js (hunk 3 above)
Comment (samussiah) [reply src/defaults/settings.js]: So that the multiples in the ID view can be resized manually.  This is necessary so that they don't overlap the right justified titles.

File: src/callbacks/onResize.js (hunk 1 above)
Comment (jwildfire) [reply src/callbacks/onResize.js]: Oh IE.
